export interface DetailsRequest {
  /**
   * The internal Nominatim database identifier for a specific place.
   * If provided, `osmtype` and `osmid` are ignored.
   * @example 4567123
   */
  place_id?: number;

  /**
   * The OpenStreetMap structural item code. Must be combined with `osmid`.
   * `N` = Node, `W` = Way, `R` = Relation.
   */
  osmtype?: "N" | "W" | "R";

  /**
   * The numeric ID of the OpenStreetMap feature. Must be combined with `osmtype`.
   * @example 240109189
   */
  osmid?: number;

  /**
   * Optional optimization filter to isolate results to a specific OSM class.
   * @example 'boundary'
   */
  class?: string;

  /**
   * Output formatting constraint. The Details endpoint only natively supports JSON for structural responses.
   * @default 'json'
   */
  format: "json";

  /**
   * Include a structured breakdown array tracking the localized elements of the address.
   * @default false
   */
  addressdetails?: boolean;

  /**
   * Include searchable lookup keyword indexes used for internal mapping calculations.
   * @default false
   */
  keywords?: boolean;

  /**
   * Include linked sub-elements or parent records sharing the internal geography.
   * @default false
   */
  linkedplaces?: boolean;

  /**
   * Output a structural parent-child tree mapping the exact administrative hierarchy levels.
   * @default false
   */
  hierarchy?: boolean;
  group_hierarchy?: boolean;

  /**
   * Output full high-fidelity GeoJSON geometries alongside base parameters.
   * @default false
   */
  polygon_geojson?: boolean;

  /**
   * Preferred language fallback constraints list string.
   * @example 'fr,en'
   * @default 'unset'
   */
  accept_language?: string;
}

export interface DetailsResponse {
  /** The internal unique identifier integer assigned by Nominatim. */
  place_id: number;

  /** Index state code representing whether the feature is fully searchable. */
  indexing_status: number;

  /** The primary OSM type string classification. */
  type: string;

  /** The primary OSM class mapping string. */
  class: string;

  /** Dynamic collection of localized descriptive name keys mapped directly from OSM data. */
  name: Record<string, string>;

  /** Structural details containing address level array breakdown objects if requested. */
  address?: any[];

  /** Additional dynamic tag metadata elements matching the place layout. */
  extratags?: Record<string, string>;

  /** Structural geometry object mapping coordinates if active. */
  geometry?: {
    type: string;
    coordinates: any;
  };
  polygon_geojson?: boolean;
  /** Dynamic catch-all signature for complex trees generated by parameters like hierarchy and keywords. */
  [key: string]: any;
}
